In [345]:
import pandas as pd
import unicodedata
from datetime import datetime

In [346]:
df_customers = pd.read_csv("data/olist_customers_dataset.csv")

In [347]:
df_geo = pd.read_csv("data/olist_geolocation_dataset.csv")

In [348]:
df_order_items = pd.read_csv("data/olist_order_items_dataset.csv")

In [349]:
df_order_payments = pd.read_csv("data/olist_order_payments_dataset.csv")

In [350]:
df_order_reviews = pd.read_csv("data/olist_order_reviews_dataset.csv")

In [351]:
df_orders = pd.read_csv("data/olist_orders_dataset.csv")

In [352]:
df_products = pd.read_csv("data/olist_products_dataset.csv")

In [353]:
df_sellers = pd.read_csv("data/olist_sellers_dataset.csv")

In [354]:
df_product_category_name_translation = pd.read_csv("data/product_category_name_translation.csv")

In [355]:
df_customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [356]:
df_geo

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [357]:
df_products

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [358]:
df_customers['customer_zip_code_prefix'] = df_customers['customer_zip_code_prefix'].astype(str)

df_customers['customer_zip_code_prefix'] = df_customers['customer_zip_code_prefix'].str.zfill(5)

In [359]:
condition = df_customers['customer_zip_code_prefix'].str.contains(f'^0\\d+', na=False, regex=True)

df_customers.loc[condition, 'customer_zip_code_prefix'].value_counts()

customer_zip_code_prefix
07600    75
09371    56
06900    46
06454    45
06730    44
         ..
01205     1
03871     1
04319     1
03727     1
05538     1
Name: count, Length: 3869, dtype: int64

In [360]:
df_geo['geolocation_zip_code_prefix'] = df_geo['geolocation_zip_code_prefix'].astype(str)

df_geo['geolocation_zip_code_prefix'] = df_geo['geolocation_zip_code_prefix'].str.zfill(5)

In [361]:
condition = df_geo['geolocation_zip_code_prefix'].str.contains(f'^[1-9]\\d*', na=False, regex=True)

df_geo.loc[condition, 'geolocation_zip_code_prefix'].value_counts()

geolocation_zip_code_prefix
24220    1146
24230    1102
38400     965
35500     907
11680     879
         ...
97843       1
97960       1
98320       1
98825       1
99839       1
Name: count, Length: 14661, dtype: int64

In [362]:
condition = df_geo['geolocation_zip_code_prefix'].str.contains(f'^0\\d*', na=False, regex=True)

df_geo.loc[condition, 'geolocation_zip_code_prefix'].value_counts()

geolocation_zip_code_prefix
07600    587
06454    532
06900    447
06543    436
06730    431
        ...
09602      1
09611      1
09696      1
09869      1
09838      1
Name: count, Length: 4354, dtype: int64

In [363]:
df_geo

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,01037,-23.545621,-46.639292,sao paulo,SP
1,01046,-23.546081,-46.644820,sao paulo,SP
2,01046,-23.546129,-46.642951,sao paulo,SP
3,01041,-23.544392,-46.639499,sao paulo,SP
4,01035,-23.541578,-46.641607,sao paulo,SP
...,...,...,...,...,...
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

In [364]:
def clean_unicode(text):
    if not isinstance(text, str):
        return text
    
    text = text.lower().strip()
    
    cleaned_text = ''.join(c for c in unicodedata.normalize('NFD', text) if unicodedata.category(c) != 'Mn')
    
    return cleaned_text

Start Cleaning Geolocation City in geo dataset

In [365]:
df_geo['geolocation_city'] = df_geo['geolocation_city'].str.lower()

df_geo['geolocation_city'] = df_geo['geolocation_city'].str.strip()

In [366]:
df_geo['geolocation_city'] = df_geo['geolocation_city'].apply(clean_unicode)

In [367]:
df_geo[df_geo['geolocation_city'].str.contains("paulo")]['geolocation_city'].value_counts()

geolocation_city
sao paulo                      160718
paulo afonso                      434
engenheiro paulo de frontin        81
paulo de faria                     56
paulo frontin                      45
monsenhor paulo                    25
sao paulo das missoes              25
paulo lopes                        22
sao paulo do potengi               18
frei paulo                         11
paulo bento                         8
paulo jacinto                       7
paulo ramos                         7
morro de sao paulo                  3
saopaulo                            2
sao paulo de olivenca               2
sa£o paulo                          1
Name: count, dtype: int64

In [368]:
df_geo[df_geo['geolocation_city'] == 'são paulo']['geolocation_zip_code_prefix']

Series([], Name: geolocation_zip_code_prefix, dtype: str)

In [369]:
sao_paulo_dirty = ['sao paulo', 'são paulo', 'sãopaulo', 'sa£o paulo', 'saopaulo']

df_geo['geolocation_city'] = df_geo['geolocation_city'].replace(sao_paulo_dirty, 'sao paulo')

In [370]:
dominant_city = df_geo.groupby('geolocation_zip_code_prefix')['geolocation_city'].agg(lambda x: x.value_counts().index[0])

In [371]:
dominant_city

geolocation_zip_code_prefix
01001          sao paulo
01002          sao paulo
01003          sao paulo
01004          sao paulo
01005          sao paulo
              ...
99960            charrua
99965         agua santa
99970            ciriaco
99980    david canabarro
99990          muliterno
Name: geolocation_city, Length: 19015, dtype: str

In [372]:
df_geo['geolocation_city'] = df_geo['geolocation_zip_code_prefix'].map(dominant_city)

Start Cleaning customer city in customers dataset

1. pakai replace series by list
2. pakai unicode
3. pakai dominant city by zip code

In [373]:
df_customers[df_customers['customer_city'].str.contains('paulo')]['customer_city'].value_counts()

customer_city
sao paulo                      15540
paulo afonso                      40
engenheiro paulo de frontin        6
paulo frontin                      5
paulo de faria                     5
paulo lopes                        2
paulo jacinto                      2
sao paulo do potengi               2
sao paulo das missoes              2
morro de sao paulo                 1
monsenhor paulo                    1
Name: count, dtype: int64

Products dataset cleaning

In [374]:
df_products['product_category_name'].isna().sum()

np.int64(610)

In [375]:
columns_rename = {
    'product_name_lenght': 'product_name_length',
    'product_description_lenght': 'product_description_length',
    'product_height_cm': 'product_heigth_cm'
}

df_products = df_products.rename(columns=columns_rename)

In [376]:
df_products.columns

Index(['product_id', 'product_category_name', 'product_name_length',
       'product_description_length', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_heigth_cm', 'product_width_cm'],
      dtype='str')

In [377]:
df_products.dtypes

product_id                        str
product_category_name             str
product_name_length           float64
product_description_length    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_heigth_cm             float64
product_width_cm              float64
dtype: object

In [378]:
columns = ['product_name_length', 'product_description_length', 'product_photos_qty']

for col in columns:
    df_products[col] = df_products[col].astype('Int64')

In [379]:
df_products.dtypes

product_id                        str
product_category_name             str
product_name_length             Int64
product_description_length      Int64
product_photos_qty              Int64
product_weight_g              float64
product_length_cm             float64
product_heigth_cm             float64
product_width_cm              float64
dtype: object

In [380]:
df_products[df_products['product_weight_g'] == 0]

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_heigth_cm,product_width_cm
9769,81781c0fed9fe1ad6e8c81fca1e1cb08,cama_mesa_banho,51,529,1,0.0,30.0,25.0,30.0
13683,8038040ee2a71048d4bdbbdc985b69ab,cama_mesa_banho,48,528,1,0.0,30.0,25.0,30.0
14997,36ba42dd187055e1fbe943b2d11430ca,cama_mesa_banho,53,528,1,0.0,30.0,25.0,30.0
32079,e673e90efa65a5409ff4196c038bb5af,cama_mesa_banho,53,528,1,0.0,30.0,25.0,30.0

In [381]:
df_products[df_products['product_weight_g'].isna()]

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_heigth_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60,865,3,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN

In [382]:
df_products["valid_product_weight_g"] = (df_products['product_weight_g'].notna()) & (df_products['product_weight_g'] > 0)

In [383]:
df_products

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_heigth_cm,product_width_cm,valid_product_weight_g
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40,287,1,225.0,16.0,10.0,14.0,True
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44,276,1,1000.0,30.0,18.0,20.0,True
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46,250,1,154.0,18.0,9.0,15.0,True
3,cef67bcfe19066a932b7673e239eb23d,bebes,27,261,1,371.0,26.0,4.0,26.0,True
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37,402,4,625.0,20.0,17.0,13.0,True
...,...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45,67,2,12300.0,40.0,40.0,40.0,True
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41,971,1,1700.0,16.0,19.0,16.0,True
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50,799,1,1400.0,27.0,7.0,27.0,True
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60,156,2,700.0,31.0,13.0,20.0,True
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58,309,1,2083.0,12.0,2.0,7.0,True

In [384]:
length_mean = df_products.groupby('product_category_name')['product_length_cm'].transform('mean')
height_mean = df_products.groupby('product_category_name')['product_heigth_cm'].transform('mean')
width_mean = df_products.groupby('product_category_name')['product_width_cm'].transform('mean')

df_products['product_length_cm'] = df_products['product_length_cm'].fillna(length_mean)
df_products['product_heigth_cm'] = df_products['product_heigth_cm'].fillna(height_mean)
df_products['product_width_cm'] = df_products['product_width_cm'].fillna(width_mean)

In [385]:
df_products[df_products['product_id'] == '09ff539a621711667c43eba6a3bd8466']

,product_id,product_category_name,product_name_length,product_description_length,product_photos_qty,product_weight_g,product_length_cm,product_heigth_cm,product_width_cm,valid_product_weight_g
8578,09ff539a621711667c43eba6a3bd8466,bebes,60,865,3,NaN,37.147059,21.617647,28.717865,False

In [386]:
length_mean = df_products['product_length_cm'].mean()
height_mean = df_products['product_heigth_cm'].mean()
width_mean = df_products['product_width_cm'].mean()

df_products['product_length_cm'] = df_products['product_length_cm'].fillna(length_mean)
df_products['product_heigth_cm'] = df_products['product_heigth_cm'].fillna(height_mean)
df_products['product_width_cm'] = df_products['product_width_cm'].fillna(width_mean)

In [387]:
unknown_category_ids = df_products[df_products['product_category_name'].isna()]['product_id']
    
df_products.loc[df_products['product_id'].isin(unknown_category_ids), 'product_category_name'] = "unknown category"

In [388]:
df_products['product_category_name'].isna().sum()

np.int64(0)

In [389]:
df_products[df_products['product_id'] == '09ff539a621711667c43eba6a3bd8466'][
    ['product_category_name', 'product_weight_g', 
     'product_length_cm', 'product_heigth_cm', 'product_width_cm']
]

,product_category_name,product_weight_g,product_length_cm,product_heigth_cm,product_width_cm
8578,bebes,NaN,37.147059,21.617647,28.717865

In [390]:
print(df_orders.dtypes)

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [391]:
print(df_orders.isna().sum())

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [392]:
print(df_order_items.dtypes)

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [393]:
print(df_order_items.isna().sum())

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [394]:
df_customers.dtypes

customer_id                 str
customer_unique_id          str
customer_zip_code_prefix    str
customer_city               str
customer_state              str
dtype: object

In [395]:
df_orders.head(20)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01 00:00:00
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07 00:00:00
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06 00:00:00
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23 00:00:00
10,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,delivered,2017-05-16 19:41:10,2017-05-16 19:50:18,2017-05-18 11:40:40,2017-05-29 11:18:31,2017-06-07 00:00:00
11,34513ce0c4fab462a55830c0989c7edb,7711cf624183d843aafe81855097bc37,delivered,2017-07-13 19:58:11,2017-07-13 20:10:08,2017-07-14 18:43:29,2017-07-19 14:04:48,2017-08-08 00:00:00
12,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,delivered,2018-06-07 10:06:19,2018-06-09 03:13:12,2018-06-11 13:29:00,2018-06-19 12:05:52,2018-07-18 00:00:00
13,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,delivered,2018-07-25 17:44:10,2018-07-25 17:55:14,2018-07-26 13:16:00,2018-07-30 15:52:25,2018-08-08 00:00:00
14,432aaf21d85167c2c86ec9448c4e42cc,3df704f53d3f1d4818840b34ec672a9f,delivered,2018-03-01 14:14:28,2018-03-01 15:10:47,2018-03-02 21:09:20,2018-03-12 23:36:26,2018-03-21 00:00:00
15,dcb36b511fcac050b97cd5c05de84dc3,3b6828a50ffe546942b7a473d70ac0fc,delivered,2018-06-07 19:03:12,2018-06-12 23:31:02,2018-06-11 14:54:00,2018-06-21 15:34:32,2018-07-04 00:00:00
16,403b97836b0c04a622354cf531062e5f,738b086814c6fcc74b8cc583f8516ee3,delivered,2018-01-02 19:00:43,2018-01-02 19:09:04,2018-01-03 18:19:09,2018-01-20 01:38:59,2018-02-06 00:00:00
17,116f0b09343b49556bbad5f35bee0cdf,3187789bec990987628d7a9beb4dd6ac,delivered,2017-12-26 23:41:31,2017-12-26 23:50:22,2017-12-28 18:33:05,2018-01-08 22:36:36,2018-01-29 00:00:00
18,85ce859fd6dc634de8d2f1e290444043,059f7fc5719c7da6cbafe370971a8d70,delivered,2017-11-21 00:03:41,2017-11-21 00:14:22,2017-11-23 21:32:26,2017-11-27 18:28:00,2017-12-11 00:00:00
19,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,delivered,2017-10-26 15:54:26,2017-10-26 16:08:14,2017-10-26 21:46:53,2017-11-08 22:22:00,2017-11-23 00:00:00

In [396]:
df_customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,09790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,01151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,08775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,03937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,06764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,06703,cotia,SP

In [397]:
df_orders_customers_joined = df_orders.merge(df_customers[['customer_id', 'customer_unique_id']], on='customer_id')

df_orders_customers_joined

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6
...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,6359f309b166b0196dbf7ad2ac62bb5a
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,da62f9e57a76d978d02ab5362c509660
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,737520a9aad80b3fbbdad19b66b37b30
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,60350aa974b26ff12caad89e55993bd6

In [398]:
df_orders_counted = df_orders_customers_joined.groupby('customer_unique_id')['order_id'].count().reset_index(name='count')

kondisi = df_orders_counted['count'] > 1

df_orders_counted_more_than_one = df_orders_counted.loc[kondisi, ['count', 'customer_unique_id']]

repeat_customer = df_orders_counted_more_than_one[df_orders_counted_more_than_one['count'] > 1].shape[0]

df_orders_counted_more_than_one

       count                customer_unique_id
33         2  00172711b30d52eea8b313a7f2cced02
106        2  004288347e5e88a27ded2bb23747066c
124        2  004b45ec5c64187465168251cd1c9c2f
144        2  0058f300f57d7b93c477a131a59b36c3
249        2  00a39521eb40f7012db50455bf083460
...      ...                               ...
95784      3  ff36be26206fffe1eb37afd54c70e18b
95810      2  ff44401d0d8f5b9c54a47374eb48c1b8
95916      2  ff8892f7c26aa0446da53d01b18df463
95934      3  ff922bdd6bafcdf99cb90d7f39cea5b3
96050      2  ffe254cc039740e17dd15a5305035928

[2997 rows x 2 columns]

In [399]:
f"Total repeat customers: {repeat_customer}"

'Total repeat customers: 2997'

In [400]:
df_orders_customers_joined[df_orders_customers_joined['customer_unique_id'] == 'ff36be26206fffe1eb37afd54c70e18b']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id
21189,b02682757340133856bfb99145dd61cd,13362fc2728edd1397282bb32cf319c1,shipped,2018-07-28 15:49:27,2018-07-28 16:24:00,2018-07-30 12:27:00,NaN,2018-08-13 00:00:00,ff36be26206fffe1eb37afd54c70e18b
22231,81b7c7bbc8ec003eeb67d87441a6a148,75c6e03e7206bd1dd59f427c9f75142a,canceled,2018-08-20 09:03:23,NaN,NaN,NaN,2018-09-03 00:00:00,ff36be26206fffe1eb37afd54c70e18b
79490,47282cfe5747c1c19920f090e491d285,3483b2a9e678865616e7d1b69b28dd4c,canceled,2018-08-23 12:38:08,NaN,NaN,NaN,2018-09-06 00:00:00,ff36be26206fffe1eb37afd54c70e18b

In [401]:
df_orders_customers_joined[df_orders_customers_joined['customer_unique_id'] == 'ff922bdd6bafcdf99cb90d7f39cea5b3']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id
31689,6be1646fccbb69d34b22da3b1807d51d,bec0bf00ac5bee64ce8ef5283051a70c,delivered,2017-09-14 14:24:04,2017-09-14 14:39:31,2017-09-14 20:43:36,2017-09-18 20:47:54,2017-10-02 00:00:00,ff922bdd6bafcdf99cb90d7f39cea5b3
35245,5f79e2da24a52e76bc22897df03a7901,d064be88116eb8b958727aec4cf56a59,delivered,2017-08-23 13:15:29,2017-08-23 13:30:19,2017-09-22 13:45:55,2017-09-25 21:34:47,2017-09-21 00:00:00,ff922bdd6bafcdf99cb90d7f39cea5b3
73622,fd216c435fda2be27c92920a5e5dba82,1ae563fdfa500d150be6578066d83998,delivered,2017-02-22 12:26:42,2017-02-22 13:05:25,2017-02-23 13:26:17,2017-03-08 02:02:59,2017-03-23 00:00:00,ff922bdd6bafcdf99cb90d7f39cea5b3

In [402]:
df_orders_customers_joined[df_orders_customers_joined['customer_unique_id'] == 'ff8892f7c26aa0446da53d01b18df463']

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id
51790,cb6e8d89049744886ad04520d5e0b2f6,62a2c35611e8757e40fbbcecb3c9b2bd,delivered,2017-05-24 16:09:14,2017-05-24 16:22:42,2017-05-25 13:15:25,2017-06-09 04:55:26,2017-06-26 00:00:00,ff8892f7c26aa0446da53d01b18df463
69852,1c308eca3f339414a92e518e2a2e5ee9,e53e1eedc9ebf9fa7a3318c60ece1d25,delivered,2017-11-26 23:25:43,2017-11-26 23:34:29,2017-11-27 21:07:09,2018-01-23 14:37:27,2017-12-29 00:00:00,ff8892f7c26aa0446da53d01b18df463

In [403]:
df_order_items

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [404]:
df_order_reviews.groupby('order_id')['review_id'].count().value_counts()

review_id
1    98126
2      543
3        4
Name: count, dtype: int64

In [405]:
multi_review_orders = df_order_reviews.groupby('order_id')['review_id'].count()
multi_review_orders_ids = multi_review_orders[multi_review_orders > 1].index

multi_review_data = df_order_reviews[df_order_reviews['order_id'].isin(multi_review_orders_ids)]

multi_review_data.sort_values(['order_id', 'review_creation_date']).head(10)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
22423,2a74b0559eb58fc1ff842ecc999594cb,0035246a40f520710769010f752e7507,5,NaN,Estou acostumada a comprar produtos pelo barat...,2017-08-25 00:00:00,2017-08-29 21:45:57
25612,89a02c45c340aeeb1354a24e7d4b2c1e,0035246a40f520710769010f752e7507,5,NaN,NaN,2017-08-29 00:00:00,2017-08-30 01:59:12
22779,ab30810c29da5da8045216f0f62652a2,013056cfe49763c6f66bda03396c5ee3,5,NaN,NaN,2018-02-22 00:00:00,2018-02-23 12:12:30
68633,73413b847f63e02bc752b364f6d05ee9,013056cfe49763c6f66bda03396c5ee3,4,NaN,NaN,2018-03-04 00:00:00,2018-03-05 17:02:00
854,830636803620cdf8b6ffaf1b2f6e92b2,0176a6846bcb3b0d3aa3116a9a768597,5,NaN,NaN,2017-12-30 00:00:00,2018-01-02 10:54:06
83224,d8e8c42271c8fb67b9dad95d98c8ff80,0176a6846bcb3b0d3aa3116a9a768597,5,NaN,NaN,2017-12-30 00:00:00,2018-01-02 10:54:47
89888,0c8e7347f1cdd2aede37371543e3d163,02355020fd0a40a0d56df9f6ff060413,3,NaN,UM DOS PRODUTOS (ENTREGA02) COMPRADOS NESTE PE...,2018-03-21 00:00:00,2018-03-22 01:32:08
17582,017f0e1ea6386de662cbeba299c59ad1,02355020fd0a40a0d56df9f6ff060413,1,NaN,ja reclamei varias vezes e ate hoje não sei on...,2018-03-29 00:00:00,2018-03-30 03:16:19
37911,04d945e95c788a3aa1ffbee42105637b,029863af4b968de1e5d6a82782e662f5,5,NaN,NaN,2017-07-14 00:00:00,2017-07-17 13:58:06
55137,61fe4e7d1ae801bbe169eb67b86c6eda,029863af4b968de1e5d6a82782e662f5,4,NaN,NaN,2017-07-19 00:00:00,2017-07-20 12:06:11

In [406]:
df_order_reviews_deduped = df_order_reviews.sort_values(by='review_creation_date', ascending=False).drop_duplicates(subset='order_id', keep='first')

df_order_reviews = df_order_reviews_deduped

### Save to staged folder

In [407]:
dataFrames = {
    "customers": df_customers,
    "geolocation": df_geo,
    "order_items": df_order_items,
    "orders": df_orders,
    "products": df_products,
    "product_category_name_translation": df_product_category_name_translation,
    "reviews": df_order_reviews
}

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

for name, df in dataFrames.items():    
    file_path = f"staged/{name}_{timestamp}.csv"
    
    df.to_csv(file_path, index=False)
    
    print(f"{file_path} berhasil disimpan")

staged/customers_20260702_115607.csv berhasil disimpan
staged/geolocation_20260702_115607.csv berhasil disimpan
staged/order_items_20260702_115607.csv berhasil disimpan
staged/orders_20260702_115607.csv berhasil disimpan
staged/products_20260702_115607.csv berhasil disimpan
staged/product_category_name_translation_20260702_115607.csv berhasil disimpan
staged/reviews_20260702_115607.csv berhasil disimpan

In [408]:
df_orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [409]:
before_purchase_timestamp_column = df_orders['order_purchase_timestamp'].isna().sum()
df_orders['order_purchase_timestamp'] = pd.to_datetime(df_orders['order_purchase_timestamp'], errors="coerce")
after_purchase_timestamp_column = df_orders['order_purchase_timestamp'].isna().sum()

failed = after_purchase_timestamp_column - before_purchase_timestamp_column

print("Jumlah gagal:", failed)

Jumlah gagal: 0

In [410]:
before_approved_at_column = df_orders['order_approved_at'].isna().sum()
df_orders['order_approved_at'] = pd.to_datetime(df_orders['order_approved_at'], errors="coerce")
after_approved_at_column = df_orders['order_approved_at'].isna().sum()

failed = after_approved_at_column - before_approved_at_column

print("Jumlah gagal:", failed)

Jumlah gagal: 0

In [411]:
before_delivered_carrier_date_column = df_orders['order_delivered_carrier_date'].isna().sum()
df_orders['order_delivered_carrier_date'] = pd.to_datetime(df_orders['order_delivered_carrier_date'], errors="coerce")
after_delivered_carrier_date_column = df_orders['order_delivered_carrier_date'].isna().sum()

failed = after_delivered_carrier_date_column - before_delivered_carrier_date_column

print("Jumlah gagal:", failed)

Jumlah gagal: 0

In [412]:
before_delivered_customer_date_column = df_orders['order_delivered_customer_date'].isna().sum()
df_orders['order_delivered_customer_date'] = pd.to_datetime(df_orders['order_delivered_customer_date'], errors="coerce")
after_delivered_customer_date_column = df_orders['order_delivered_customer_date'].isna().sum()

failed = after_delivered_customer_date_column - before_delivered_customer_date_column

print("Jumlah gagal:", failed)

Jumlah gagal: 0

In [413]:
before_estimated_delivery_date_column = df_orders['order_estimated_delivery_date'].isna().sum()
df_orders['order_estimated_delivery_date'] = pd.to_datetime(df_orders['order_estimated_delivery_date'], errors="coerce")
after_estimated_delivery_date_column = df_orders['order_estimated_delivery_date'].isna().sum()

failed = after_estimated_delivery_date_column - before_estimated_delivery_date_column

print("Jumlah gagal:", failed)

Jumlah gagal: 0

In [414]:
list_columns = [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date'
]

list_of_failed = []

for column in list_columns:
    before = df_orders[column].isna().sum()
    df_orders[column] = pd.to_datetime(df_orders[column], errors="coerce")
    after = df_orders[column].isna().sum()
    
    count_failed = after - before
    
    list_of_failed.append(count_failed)

for column, failed in zip(list_columns, list_of_failed):
    print(f"failed {column}: {failed} item(s)")

failed order_purchase_timestamp: 0 item(s)
failed order_approved_at: 0 item(s)
failed order_delivered_carrier_date: 0 item(s)
failed order_delivered_customer_date: 0 item(s)
failed order_estimated_delivery_date: 0 item(s)

In [415]:
before = df_order_items['shipping_limit_date'].isna().sum()
df_order_items['shipping_limit_date'] = pd.to_datetime(df_order_items['shipping_limit_date'], errors="coerce")
after = df_order_items['shipping_limit_date'].isna().sum()

failed_count = after - before

print(f"failed: {failed_count}")

failed: 0

In [416]:
before = df_order_items['shipping_limit_date'].isna().sum()
df_order_items['shipping_limit_date'] = pd.to_datetime(df_order_items['shipping_limit_date'], errors="coerce")
after = df_order_items['shipping_limit_date'].isna().sum()

failed_count = after - before

print(f"failed: {failed_count}")

failed: 0

In [417]:
list_columns = [
    'review_creation_date',
    'review_answer_timestamp'
]

list_of_failed = []

for column in list_columns:
    before = df_order_reviews[column].isna().sum()
    df_order_reviews[column] = pd.to_datetime(df_order_reviews[column], errors="coerce")
    after = df_order_reviews[column].isna().sum()
    
    count_failed = after - before
    
    list_of_failed.append(count_failed)

for column, failed in zip(list_columns, list_of_failed):
    print(f"failed {column}: {failed} item(s)")

failed review_creation_date: 0 item(s)
failed review_answer_timestamp: 0 item(s)

In [418]:
df_order_payments.dtypes

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

In [419]:
df_orders.head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,delivered,2017-07-09 21:57:05,2017-07-09 22:10:13,2017-07-11 14:58:04,2017-07-26 10:57:55,2017-08-01
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaT,NaT,2017-05-09
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,delivered,2017-05-16 13:10:30,2017-05-16 13:22:11,2017-05-22 10:07:46,2017-05-26 12:55:51,2017-06-07
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,delivered,2017-01-23 18:29:09,2017-01-25 02:50:47,2017-01-26 14:16:31,2017-02-02 14:08:10,2017-03-06
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,delivered,2017-07-29 11:55:02,2017-07-29 12:05:32,2017-08-10 19:45:24,2017-08-16 17:14:30,2017-08-23

In [424]:
outlier_config = {
    "Order Items": {
        "dataframe": df_order_items,
        "columns": {
            "price": "is_price_outlier",
            "freight_value": "is_freight_value_outlier"
        }
    },
    "Order Payments": {
        "dataframe": df_order_payments,
        "columns": {
            "payment_value": "is_payment_value_outlier"
        }
    }
}

for name, config in outlier_config.items():
    
    df = config['dataframe']
    
    for col, flag in config['columns'].items():
        
        q1 = df[col].quantile(0.25)
        q3 = df[col].quantile(0.75)
        
        iqr = q3 - q1
        
        bottom_limit = q1 - 1.5 * iqr
        top_limit = q3 + 1.5 * iqr
        
        df[flag] = (df[col] < bottom_limit) | (df[col] > top_limit)
        
        total_outlier = df[flag].sum()
        presentage = (total_outlier / len(df) * 100).round(2)
        
        print(f"\n==={name}===\n")

        print(f"Total outlier: {total_outlier} ({presentage}%)")
        
        print(f"Q1: {q1}")
        print(f"Q3: {q3}")
        print(f"IQR: {iqr}")
        print(f"Bottom limit: {bottom_limit}")
        print(f"Top limit: {top_limit}\n")
        
        print(f"Jumlah yang 0 atau kurang dari 0 : {df[df[col] <= 0].shape[0]}")
        print(f"Jumlah lebih dari outlier        : {df[df[col] > top_limit].shape[0]}")
        print(f"Jumlah kurang dari outlier       : {df[df[col] < bottom_limit].shape[0]}\n")
        
        print(df.head(20))

===Order Items===

Total outlier: 8427 (7.48%)
Q1: 39.9
Q3: 134.9
IQR: 95.0
Bottom limit: -102.6
Top limit: 277.4

Jumlah yang 0 atau kurang dari 0 : 0
Jumlah lebih dari outlier        : 8427
Jumlah kurang dari outlier       : 0

                            order_id  order_item_id  \
0   00010242fe8c5a6d1ba2dd792cb16214              1
1   00018f77f2f0320c557190d7a144bdd3              1
2   000229ec398224ef6ca0657da4fc703e              1
3   00024acbcdf0a6daa1e931b038114c75              1
4   00042b26cf59d7ce69dfabb4e55b4fd9              1
5   00048cc3ae777c65dbb7d2a0634bc1ea              1
6   00054e8431b9d7675808bcb819fb4a32              1
7   000576fe39319847cbb9d288c5617fa6              1
8   0005a1a1728c9d785b8e2b08b904576c              1
9   0005f50442cb953dcd1d21e1fb923495              1
10  00061f2a7bc09da83e415a52dc8a4af1              1
11  00063b381e2406b52ad429470734ebd5              1
12  0006ec9db01a64e59a68b2c340bf65a7              1
13  0008288aa423d2a3f00fcb17cd7d8719              1
14  0008288aa423d2a3f00fcb17cd7d8719              2
15  0009792311464db532ff765bf7b182ae              1
16  0009c9a17f916a706d71784483a5d643              1
17  000aed2e25dbad2f9ddb70584c5a2ded              1
18  000c3e6612759851cc3cbb4b83257986              1
19  000e562887b1f2006d75e0be9558292e              1

                          product_id                         seller_id  \
0   4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1   e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2   c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3   7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4   ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87
5   ef92defde845ab8450f9d70c526ef70f  6426d21aca402a131fc0a5d0960a3c90
6   8d4f2bb7e93e6710a28f34fa83ee7d28  7040e82f899a04d1b434b795a43b4617
7   557d850972a7d6f792fd18ae1400d9b6  5996cddab893a4652a15592fb58ab8db
8   310ae3c140ff94b03219ad0adc3c778f  a416b6a846a11724393025641d4edd5e
9   4535b0e1091c278dfd193e5a1d63b39f  ba143b05f0110f0dc71ad71b4466ce92
10  d63c1011f49d98b976c352955b1c4bea  cc419e0650a3c5ba77189a1882b7556a
11  f177554ea93259a5b282f24e33f65ab6  8602a61d680a10a82cceeeda0d99ea3d
12  99a4788cb24856965c36a24e339b6058  4a3ca9315b744ce9f8e9374361493884
13  368c6c730842d78016ad823897a372db  1f50f920176fa81dab994f9023523100
14  368c6c730842d78016ad823897a372db  1f50f920176fa81dab994f9023523100
15  8cab8abac59158715e0d70a36c807415  530ec6109d11eaaf87999465c6afee01
16  3f27ac8e699df3d300ec4a5d8c5cf0b2  fcb5ace8bcc92f75707dc0f01a27d269
17  4fa33915031a8cde03dd0d3e8fb27f01  fe2032dab1a61af8794248c8196565c9
18  b50c950aba0dcead2c48032a690ce817  218d46b86c1881d022bce9c68a7d4b15
19  5ed9eaf534f6936b51d0b6c5e4d5c2e9  8cbac7e12637ed9cffa18c7875207478

   shipping_limit_date   price  freight_value  is_price_outlier  \
0  2017-09-19 09:45:35   58.90          13.29             False
1  2017-05-03 11:05:13  239.90          19.93             False
2  2018-01-18 14:48:30  199.00          17.87             False
3  2018-08-15 10:10:18   12.99          12.79             False
4  2017-02-13 13:57:51  199.90          18.14             False
5  2017-05-23 03:55:27   21.90          12.69             False
6  2017-12-14 12:10:31   19.90          11.85             False
7  2018-07-10 12:30:45  810.00          70.75              True
8  2018-03-26 18:31:29  145.95          11.65             False
9  2018-07-06 14:10:56   53.99          11.40             False
10 2018-03-29 22:28:09   59.99           8.88             False
11 2018-07-31 17:30:39   45.00          12.98             False
12 2018-07-26 17:24:20   74.00          23.32             False
13 2018-02-21 02:55:52   49.90          13.37             False
14 2018-02-21 02:55:52   49.90          13.37             False
15 2018-08-17 12:15:10   99.90          27.65             False
16 2018-05-02 09:31:53  639.00          11.34              True
17 2018-05-16 20:57:03  144.00           8.77             False
18 2017-08-21 03:33:13   99.00          13.71             False
19 2018-02-28 12:08:37   25.00          16.11             False

    is_freight_value_outlier
0                      False
1                      False
2                      False
3                      False
4                      False
5                      False
6                      False
7                       True
8                      False
9                      False
10                     False
11                     False
12                     False
13                     False
14                     False
15                     False
16                     False
17                     False
18                     False
19                     False

===Order Items===

Total outlier: 12134 (10.77%)
Q1: 13.08
Q3: 21.15
IQR: 8.069999999999999
Bottom limit: 0.9750000000000032
Top limit: 33.254999999999995

Jumlah yang 0 atau kurang dari 0 : 383
Jumlah lebih dari outlier        : 11613
Jumlah kurang dari outlier       : 521

                            order_id  order_item_id  \
0   00010242fe8c5a6d1ba2dd792cb16214              1
1   00018f77f2f0320c557190d7a144bdd3              1
2   000229ec398224ef6ca0657da4fc703e              1
3   00024acbcdf0a6daa1e931b038114c75              1
4   00042b26cf59d7ce69dfabb4e55b4fd9              1
5   00048cc3ae777c65dbb7d2a0634bc1ea              1
6   00054e8431b9d7675808bcb819fb4a32              1
7   000576fe39319847cbb9d288c5617fa6              1
8   0005a1a1728c9d785b8e2b08b904576c              1
9   0005f50442cb953dcd1d21e1fb923495              1
10  00061f2a7bc09da83e415a52dc8a4af1              1
11  00063b381e2406b52ad429470734ebd5              1
12  0006ec9db01a64e59a68b2c340bf65a7              1
13  0008288aa423d2a3f00fcb17cd7d8719              1
14  0008288aa423d2a3f00fcb17cd7d8719              2
15  0009792311464db532ff765bf7b182ae              1
16  0009c9a17f916a706d71784483a5d643              1
17  000aed2e25dbad2f9ddb70584c5a2ded              1
18  000c3e6612759851cc3cbb4b83257986              1
19  000e562887b1f2006d75e0be9558292e              1

                          product_id                         seller_id  \
0   4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1   e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2   c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3   7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4   ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87
5   ef92defde845ab8450f9d70c526ef70f  6426d21aca402a131fc0a5d0960a3c90
6   8d4f2bb7e93e6710a28f34fa83ee7d28  7040e82f899a04d1b434b795a43b4617
7   557d850972a7d6f792fd18ae1400d9b6  5996cddab893a4652a15592fb58ab8db
8   310ae3c140ff94b03219ad0adc3c778f  a416b6a846a11724393025641d4edd5e
9   4535b0e1091c278dfd193e5a1d63b39f  ba143b05f0110f0dc71ad71b4466ce92
10  d63c1011f49d98b976c352955b1c4bea  cc419e0650a3c5ba77189a1882b7556a
11  f177554ea93259a5b282f24e33f65ab6  8602a61d680a10a82cceeeda0d99ea3d
12  99a4788cb24856965c36a24e339b6058  4a3ca9315b744ce9f8e9374361493884
13  368c6c730842d78016ad823897a372db  1f50f920176fa81dab994f9023523100
14  368c6c730842d78016ad823897a372db  1f50f920176fa81dab994f9023523100
15  8cab8abac59158715e0d70a36c807415  530ec6109d11eaaf87999465c6afee01
16  3f27ac8e699df3d300ec4a5d8c5cf0b2  fcb5ace8bcc92f75707dc0f01a27d269
17  4fa33915031a8cde03dd0d3e8fb27f01  fe2032dab1a61af8794248c8196565c9
18  b50c950aba0dcead2c48032a690ce817  218d46b86c1881d022bce9c68a7d4b15
19  5ed9eaf534f6936b51d0b6c5e4d5c2e9  8cbac7e12637ed9cffa18c7875207478

   shipping_limit_date   price  freight_value  is_price_outlier  \
0  2017-09-19 09:45:35   58.90          13.29             False
1  2017-05-03 11:05:13  239.90          19.93             False
2  2018-01-18 14:48:30  199.00          17.87             False
3  2018-08-15 10:10:18   12.99          12.79             False
4  2017-02-13 13:57:51  199.90          18.14             False
5  2017-05-23 03:55:27   21.90          12.69             False
6  2017-12-14 12:10:31   19.90          11.85             False
7  2018-07-10 12:30:45  810.00          70.75              True
8  2018-03-26 18:31:29  145.95          11.65             False
9  2018-07-06 14:10:56   53.99          11.40             False
10 2018-03-29 22:28:09   59.99           8.88             False
11 2018-07-31 17:30:39   45.00          12.98             False
12 2018-07-26 17:24:20   74.00          23.32             False
13 2018-02-21 02:55:52   49.90          13.37             False
14 2018-02-21 02:55:52   49.90          13.37             False
15 2018-08-17 12:15:10   99.90          27.65             False
16 2018-05-02 09:31:53  639.00          11.34              True
17 2018-05-16 20:57:03  144.00           8.77             False
18 2017-08-21 03:33:13   99.00          13.71             False
19 2018-02-28 12:08:37   25.00          16.11             False

    is_freight_value_outlier
0                      False
1                      False
2                      False
3                      False
4                      False
5                      False
6                      False
7                       True
8                      False
9                      False
10                     False
11                     False
12                     False
13                     False
14                     False
15                     False
16                     False
17                     False
18                     False
19                     False

===Order Payments===

Total outlier: 7981 (7.68%)
Q1: 56.79
Q3: 171.8375
IQR: 115.04750000000001
Bottom limit: -115.78125000000003
Top limit: 344.40875000000005

Jumlah yang 0 atau kurang dari 0 : 9
Jumlah lebih dari outlier        : 7981
Jumlah kurang dari outlier       : 0

                            order_id  payment_sequential payment_type  \
0   b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1   a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2   25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3   ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4   42fdf880ba16b47b59251dd489d4441a                   1  credit_card
5   298fcdf1f73eb413e4d26d01b25bc1cd                   1  credit_card
6   771ee386b001f06208a7419e4fc1bbd7                   1  credit_card
7   3d7239c394a212faae122962df514ac7                   1  credit_card
8   1f78449c87a54faf9e96e88ba1491fa9                   1  credit_card
9   0573b5e23cbd798006520e1d5b4c6714                   1       boleto
10  d88e0d5fa41661ce03cf6cf336527646                   1  credit_card
11  2480f727e869fdeb397244a21b721b67                   1  credit_card
12  616105c9352a9668c38303ad44e056cd                   1  credit_card
13  cf95215a722f3ebf29e6bbab87a29e61                   1  credit_card
14  769214176682788a92801d8907fa1b40                   1  credit_card
15  12e5cfe0e4716b59afb0e0f4a3bd6570                   1  credit_card
16  61059985a6fc0ad64e95d9944caacdad                   1  credit_card
17  79da3f5fe31ad1e454f06f95dc032ad5                   1  credit_card
18  8ac09207f415d55acff302df7d6a895c                   1  credit_card
19  b2349a3f20dfbeef62e7b31baa22f84b                   1  credit_card

    payment_installments  payment_value  is_payment_value_outlier
0                      8          99.33                     False
1                      1          24.39                     False
2                      1          65.71                     False
3                      8         107.78                     False
4                      2         128.45                     False
5                      2          96.12                     False
6                      1          81.16                     False
7                      3          51.84                     False
8                      6         341.09                     False
9                      1          51.95                     False
10                     8         188.73                     False
11                     1         141.90                     False
12                     1          75.78                     False
13                     5         102.66                     False
14                     4         105.28                     False
15                    10         157.45                     False
16                     1         132.04                     False
17                     1          98.94                     False
18                     4         244.15                     False
19                     3         136.71                     False

In [423]:
df_order_payments[df_order_payments['payment_value'] <= 0].merge(df_orders, on='order_id')

,order_id,payment_sequential,payment_type,payment_installments,payment_value,is_payment_value_outlier,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,8bcbe01d44d147f901cd3192671144db,4,voucher,1,0.0,False,f2def7f64f36952f2f5a9791f0285f34,delivered,2018-01-24 23:24:14,2018-01-24 23:37:20,2018-01-30 22:43:30,2018-02-02 21:26:42,2018-02-21
1,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.0,False,9af2372a1e49340278e7c1ef8d749f34,shipped,2017-04-20 12:45:34,2017-04-22 09:10:13,2017-04-24 11:31:17,NaT,2017-05-18
2,6ccb433e00daae1283ccc956189c82ae,4,voucher,1,0.0,False,843b211abe7b0264dd4a69eafc5bdf43,delivered,2017-10-26 23:51:35,2017-10-27 00:46:58,2017-10-27 19:53:03,2017-11-08 18:47:00,2017-11-22
3,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0,False,a73c1f73f5772cf801434bf984b0b1a7,canceled,2018-09-03 14:14:25,NaT,NaT,NaT,2018-09-10
4,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0,False,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaT,NaT,NaT,2018-09-12
5,45ed6e85398a87c253db47c2d9f48216,3,voucher,1,0.0,False,8eab8f9b3c744b76b65f7a2c0c8f2d6c,delivered,2017-06-08 21:18:45,2017-06-08 21:30:18,2017-06-09 08:35:18,2017-06-22 17:44:53,2017-07-10
6,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.0,False,9af2372a1e49340278e7c1ef8d749f34,shipped,2017-04-20 12:45:34,2017-04-22 09:10:13,2017-04-24 11:31:17,NaT,2017-05-18
7,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0,False,197a2a6a77da93f678ea0d379f21da0a,canceled,2018-08-28 20:05:14,NaT,NaT,NaT,2018-09-11
8,b23878b3e8eb4d25a158f57d96331b18,4,voucher,1,0.0,False,648121b599d98c420ef93f6135f8c80c,delivered,2017-05-27 19:20:24,2017-05-27 19:35:17,2017-05-29 04:49:37,2017-06-07 08:53:10,2017-06-29